### ISSUE TITLE
Fatal exception SIG: 9 on Android

### ISSUE THREAD

**Issue by marcoberetta96** [CarnegieTechnologies/gallery_saver#139]
When saving an image, this null pointer exception kills the app.
Android, latest version of this package.

```
E/AndroidRuntime(16565): FATAL EXCEPTION: main
E/AndroidRuntime(16565): Process: com.marco.faceroom_test2, PID: 16565
E/AndroidRuntime(16565): java.lang.NullPointerException
E/AndroidRuntime(16565): 	at carnegietechnologies.gallery_saver.GallerySaver.finishWithSuccess(GallerySaver.kt:77)
E/AndroidRuntime(16565): 	at carnegietechnologies.gallery_saver.GallerySaver.access$finishWithSuccess(GallerySaver.kt:16)
E/AndroidRuntime(16565): 	at carnegietechnologies.gallery_saver.GallerySaver$saveMediaFile$1.invokeSuspend(GallerySaver.kt:72)
E/AndroidRuntime(16565): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(16565): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
E/AndroidRuntime(16565): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(16565): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(16565): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(16565): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
E/AndroidRuntime(16565): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16565): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(16565): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process (16565): Sending signal. PID: 16565 SIG: 9

```

**Comment by marcoberetta96** [comment]
Same issue with version 2.1.3.
Unfortunately at the moment this package is unusable because cause the entire app to crash.
Is there any news or something we can do with this?

**Comment by lecicdjuro** [comment]
Please attach additional info, 
Phone, Android OS, Flutter version

**Comment by lecicdjuro** [comment]
> Same issue with version 2.1.3.
> Unfortunately at the moment this package is unusable because cause the entire app to crash.
> Is there any news or something we can do with this?

 Please attach additional info, 
Phone, Android OS, Flutter version

**Comment by marcoberetta96** [comment]
Pixel 3a, Android 11, Flutter 2.2.3 stable

Please let me know if something else is needed. Thank you!

**Comment by pandazed** [comment]
Same problem
Xiaomi MI PAD 4, Android 8.1.0

gallery_saver: 2.1.3
Flutter 2.2.2 stable
Android SDK version 30.0.3
<details> 
  <summary>Stack trace</summary>
 

>   Fatal Exception: java.lang.NullPointerException
>     carnegietechnologies.gallery_saver.GallerySaver.finishWithSuccess (GallerySaver.java:2)
>     carnegietechnologies.gallery_saver.GallerySaver.access$finishWithSuccess (GallerySaver.java)
>     carnegietechnologies.gallery_saver.GallerySaver$saveMediaFile$1.invokeSuspend (GallerySaver.java:61)
>     kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:9)
>     kotlinx.coroutines.DispatchedTask.run (DispatchedTask.java:94)
>     android.os.Handler.handleCallback (Handler.java:2)

</details>

**Comment by lecicdjuro** [comment]
try with 2.2.0

**Comment by marcoberetta96** [comment]
@lecicdjuro 
Regret to inform that the problem is still the same.

# Log

```
E/AndroidRuntime(30144): FATAL EXCEPTION: main
E/AndroidRuntime(30144): Process: com.marco.my_app, PID: 30144
E/AndroidRuntime(30144): java.lang.NullPointerException
E/AndroidRuntime(30144): 	at carnegietechnologies.gallery_saver.GallerySaver.finishWithSuccess(GallerySaver.kt:79)
E/AndroidRuntime(30144): 	at carnegietechnologies.gallery_saver.GallerySaver.access$finishWithSuccess(GallerySaver.kt:16)
E/AndroidRuntime(30144): 	at carnegietechnologies.gallery_saver.GallerySaver$saveMediaFile$1.invokeSuspend(GallerySaver.kt:74)
E/AndroidRuntime(30144): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(30144): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
E/AndroidRuntime(30144): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(30144): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(30144): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(30144): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(30144): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime(30144): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30144): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(30144): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/Process (30144): Sending signal. PID: 30144 SIG: 9
Lost connection to device.
```

I'm trying to save this file `/data/user/0/com.marco.my_app/app_flutter/FaceRoom/Images/f0d96875248f760ef4664921bf77b409.jpeg`


# Flutter doctor

```
[✓] Flutter (Channel stable, 2.5.3)
    • Flutter version 2.5.3
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Platform android-31, build-tools 31.0.0

[✓] Connected device
    • Pixel 3a (mobile) • 948AY0KK49 • android-arm64  • Android 12 (API 31)
```

I'm using gallery_saver ^2.3.2.
Please let me know if I can provide more useful information.
As I said, unfortunately this makes the entire app crash, so at the moment this package is not usable.

**Comment by HeynSekk** [comment]
Same issue here. It still happening on gallery_saver 2.3.2. In my app, this issue has 15 crash events affecting 9 users according to crashlytics.
```
Fatal Exception: java.lang.NullPointerException
       at carnegietechnologies.gallery_saver.GallerySaver.finishWithSuccess(GallerySaver.kt:79)
       at carnegietechnologies.gallery_saver.GallerySaver.access$finishWithSuccess(GallerySaver.kt:16)
       at carnegietechnologies.gallery_saver.GallerySaver$saveMediaFile$1.invokeSuspend(GallerySaver.kt:74)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8192)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015) ```
