### ISSUE TITLE
Multiple images download

### ISSUE THREAD

**Issue by jensvrai** [CarnegieTechnologies/gallery_saver#15]
Hi guys,

Thanks for the work on this plugin.
When I use it to download a single image it works. But when I use it while looping over a set of image urls.
I have only tried it on Android

```
refAlbum.pictures.forEach((picture) {
  GallerySaver.saveImage(picture.url).then((bool success) {
    print('success');
  });
});
```
```
W/System  (10078): A resource failed to call close.
E/AndroidRuntime( 9028): FATAL EXCEPTION: main
E/AndroidRuntime( 9028): Process: xxxxxxxxxxx, PID: 9028
E/AndroidRuntime( 9028): kotlin.KotlinNullPointerException
E/AndroidRuntime( 9028): 	at carnegietechnologies.gallery_saver.GallerySaver.finishWithSuccess(GallerySaver.kt:112)
E/AndroidRuntime( 9028): 	at carnegietechnologies.gallery_saver.GallerySaver.access$finishWithSuccess(GallerySaver.kt:15)
E/AndroidRuntime( 9028): 	at carnegietechnologies.gallery_saver.GallerySaver$saveImage$1.invokeSuspend(GallerySaver.kt:91)
E/AndroidRuntime( 9028): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime( 9028): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
E/AndroidRuntime( 9028): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 9028): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 9028): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 9028): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 9028): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9028): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 9028): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W/System  ( 9028): A resource failed to call close.
I/Process ( 9028): Sending signal. PID: 9028 SIG: 9
Lost connection to device.
Exited (sigterm)
```

How can I get this to work with multiple images?

**Comment by jelenalecic** [comment]
@jensvrai 
try to use await.
await GallerySaver.saveImage....

**Comment by vlada3003** [comment]
@jelenalecic using await is just a workaround. The proper solution would be to create a new method that would accept a list of image URLs. However, I'm not sure if we have time for this right now. @jensvrai do you want to tackle this? We would gladly accept your pull request, but we won't get angry if you say no. :)
