### ISSUE TITLE
Completely Crashing the App on Android 

### ISSUE THREAD

**Issue by billymahmood** [CarnegieTechnologies/gallery_saver#30]
Hi,

Thank you for the great plugin, I am having a small issue on Android.

Device: `Samsung Galaxy SM A520F`
Running in `Debug` mode
Error on Device 'App Name has stopped working`
Plugin version gallery_saver: ^1.0.6

Checks on Device
- I have checked the device storage, and it has enough storage to save the image (a couple of GB free)
- I have added the required android permissions etc

Code
```dart
ImagePicker.pickImage(source: ImageSource.camera).then(
              (File recordedImage) async {
                if (recordedImage != null && recordedImage.path != null) {
                  try {
                    GallerySaver.saveImage(recordedImage.path); // If I remove this code, everything works fine however the image is not saved on device
                  } catch (e) {
                    print(e);
                  }
                }
              },
            );

```

Flutter Doctor 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A602, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.1)
[✓] Connected device (2 available)

• No issues found!
```

Error Messge in Android Studio
```
D/ViewRootImpl@82f00f9[MainActivity](28189): mHardwareRenderer.destroy()#1
D/ViewRootImpl@82f00f9[MainActivity](28189): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x1 surface={isValid=false 0} surfaceGenerationChanged=false
D/SurfaceView(28189): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x7 surface={Surface(name=null)/@0x6d5b3b5 isValid=true 496777930240}
D/mali_winsys(28189): EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
D/ViewRootImpl@82f00f9[MainActivity](28189): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x7 surface={isValid=true 496087858176} surfaceGenerationChanged=true
D/ViewRootImpl@82f00f9[MainActivity](28189): mHardwareRenderer.initialize() mSurface={isValid=true 496087858176} hwInitialized=true
D/mali_winsys(28189): EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
D/ViewRootImpl@82f00f9[MainActivity](28189): MSG_WINDOW_FOCUS_CHANGED 1
D/ViewRootImpl@82f00f9[MainActivity](28189): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 496087858176}
V/InputMethodManager(28189): Starting input: tba=android.view.inputmethod.EditorInfo@e01b523 nm : co.uk.gallagherltd.gard ic=null
I/InputMethodManager(28189): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(28189): Input channel constructed: fd=94
I/ExifInterface_JNI(28189): Raw image not detected
I/ExifInterface(28189): innerIfdHint: 1
I/ExifInterface(28189): innerIfdHint: 3
W/ExifInterface(28189): Skip the tag entry since tag number is not defined: 2
I/ExifInterface(28189): innerIfdHint: 2
I/ExifInterface_JNI(28189): Raw image not detected
I/art     (28189): Starting a blocking GC Alloc
I/art     (28189): Starting a blocking GC Alloc
I/art     (28189): Alloc sticky concurrent mark sweep GC freed 2175(166KB) AllocSpace objects, 0(0B) LOS objects, 11% free, 84MB/96MB, paused 258us total 8.544ms
I/art     (28189): Starting a blocking GC Alloc
I/art     (28189): Alloc partial concurrent mark sweep GC freed 301(9KB) AllocSpace objects, 3(73MB) LOS objects, 40% free, 11MB/19MB, paused 246us total 31.361ms
I/art     (28189): Waiting for a blocking GC Alloc
I/art     (28189): WaitForGcToComplete blocked for 11.159ms for cause Alloc
I/art     (28189): Starting a blocking GC Alloc
I/art     (28189): Starting a blocking GC Alloc
I/art     (28189): Starting a blocking GC Alloc
I/art     (28189): Alloc partial concurrent mark sweep GC freed 8(200B) AllocSpace objects, 0(0B) LOS objects, 18% free, 72MB/88MB, paused 235us total 14.360ms
I/art     (28189): Starting a blocking GC Alloc
I/art     (28189): Alloc concurrent mark sweep GC freed 47(17KB) AllocSpace objects, 0(0B) LOS objects, 18% free, 72MB/88MB, paused 256us total 39.811ms
I/art     (28189): Forcing collection of SoftReferences for 60MB allocation
I/art     (28189): Starting a blocking GC Alloc
I/art     (28189): Alloc concurrent mark sweep GC freed 42(1872B) AllocSpace objects, 0(0B) LOS objects, 18% free, 72MB/88MB, paused 386us total 39.266ms
W/art     (28189): Throwing OutOfMemoryError "Failed to allocate a 63701004 byte allocation with 16777216 free bytes and 55MB until OOM"
I/art     (28189): Starting a blocking GC Alloc
I/art     (28189): Starting a blocking GC Alloc
I/art     (28189): Starting a blocking GC Alloc
I/art     (28189): Alloc partial concurrent mark sweep GC freed 6(144B) AllocSpace objects, 0(0B) LOS objects, 18% free, 72MB/88MB, paused 303us total 14.218ms
I/art     (28189): Starting a blocking GC Alloc
I/art     (28189): Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 18% free, 72MB/88MB, paused 417us total 40.005ms
I/art     (28189): Forcing collection of SoftReferences for 60MB allocation
I/art     (28189): Starting a blocking GC Alloc
I/art     (28189): Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 18% free, 72MB/88MB, paused 280us total 40.051ms
W/art     (28189): Throwing OutOfMemoryError "Failed to allocate a 63701004 byte allocation with 16777216 free bytes and 55MB until OOM"
E/AndroidRuntime(28189): FATAL EXCEPTION: DefaultDispatcher-worker-1
E/AndroidRuntime(28189): Process: co.uk.gallagherltd.gard, PID: 28189
E/AndroidRuntime(28189): java.lang.OutOfMemoryError: Failed to allocate a 63701004 byte allocation with 16777216 free bytes and 55MB until OOM
E/AndroidRuntime(28189): 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
E/AndroidRuntime(28189): 	at android.graphics.Bitmap.nativeCreate(Native Method)
E/AndroidRuntime(28189): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
E/AndroidRuntime(28189): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
E/AndroidRuntime(28189): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
E/AndroidRuntime(28189): 	at carnegietechnologies.gallery_saver.FileUtils.getRotatedBytesIfNecessary(FileUtils.kt:119)
E/AndroidRuntime(28189): 	at carnegietechnologies.gallery_saver.FileUtils.insertImage(FileUtils.kt:49)
E/AndroidRuntime(28189): 	at carnegietechnologies.gallery_saver.GallerySaver$saveMediaFile$1$success$1.invokeSuspend(GallerySaver.kt:69)
E/AndroidRuntime(28189): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(28189): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
E/AndroidRuntime(28189): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
E/AndroidRuntime(28189): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
E/AndroidRuntime(28189): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
D/ViewRootImpl@82f00f9[MainActivity](28189): MSG_WINDOW_FOCUS_CHANGED 0
D/SurfaceView(28189): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x5 surface={Surface(name=null)/@0x6d5b3b5 isValid=false 0}
D/ViewRootImpl@82f00f9[MainActivity](28189): mHardwareRenderer.destroy()#1
D/ViewRootImpl@82f00f9[MainActivity](28189): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
D/ViewRootImpl@82f00f9[MainActivity](28189): mHardwareRenderer.destroy()#4
D/ViewRootImpl@82f00f9[MainActivity](28189): dispatchDetachedFromWindow
D/InputTransport(28189): Input channel destroyed: fd=84
```

**Comment by jelenalecic** [comment]
@billy124 
Hmmm, I believe this is happening because we try to rotate image if orientation was wrong, take a look here - https://stackoverflow.com/questions/8346955/android-camera-resulted-image-should-be-rotated-after-the-capture/18959674#18959674.
We detect this and try to rotate it, but to do so, we need to load image in memory, rotate it, and save it at the end. This is probably a low memory telephone.

**Comment by billy124** [comment]
Is it possible to avoid the orientation fix on low memory phones?

**Comment by jelenalecic** [comment]
@billy124 
sorry, but no at the moment.

**Comment by billy124** [comment]
So it looks like these lines are causing the issue in the file FileUtils.kt - I've never developed Plugins in the past so I could be wrong however is it possible for me to modify the code so that pickImage take a new param such as `rotatedBytes` and in the Kotlin side we only run the below code if that's set to true?

`val rotatedBytes = getRotatedBytesIfNecessary(source, path)
if (rotatedBytes != null) {
            source = rotatedBytes
        }
`

**Comment by myriky** [comment]
same here.

**Comment by jelenalecic** [comment]
Sorry, we do not support low memory telephones :)
