### ISSUE TITLE
twice save expection  

### ISSUE THREAD

**Issue by alienzh** [CarnegieTechnologies/gallery_saver#37]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getLastPathSegment()' on a null object reference
        at android.content.ContentUris.parseId(ContentUris.java:85)
        at carnegietechnologies.gallery_saver.FileUtils.insertImage(FileUtils.kt:79)
        at carnegietechnologies.gallery_saver.GallerySaver$saveMediaFile$1$success$1.invokeSuspend(GallerySaver.kt:69)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

Fileutils line 67
  imageUri = contentResolver.insert(imageUri, values) 
This method will return null for two saves

**Comment by jinzekid** [comment]
It maybe happened on Android.
Here is Solution:
static Future<File> _downloadFile(String url) async {
    print(url);
    http.Client _client = new http.Client();
    var req = await _client.get(Uri.parse(url));
    var bytes = req.bodyBytes;
    String dir = (await getTemporaryDirectory()).path;

    // bug: 同样url在android手机上会崩溃
    // fixed: 获得一个唯一时间戳用于给图片命名，避免重复url的下载
    DateTime time = DateTime.now();
    final String uuid = time.millisecondsSinceEpoch.toString();
    
    File file = new File('$dir/${uuid}_${basename(url)}');
    await file.writeAsBytes(bytes);
    print('File size:${await file.length()}');
    print(file.path);
    return file;
  }

**Comment by pmrajani** [comment]
@alienzh @jinzekid @marko-gacesa @MegaManX32 @zoromatic  Any solution for this? app crash if we   download it twice.

**Comment by martintadashi** [comment]
Any solution for this?

**Comment by CircleOnCircles** [comment]
Any updates?

**Comment by jelenalecic** [comment]
@CircleOnCircles @martintadashi @pmrajani @jinzekid @alienzh 

merged.
sorry for taking this long, but we were very busy.
hope you're still using this plugin :)

**Comment by CircleOnCircles** [comment]
> @CircleOnCircles @martintadashi @pmrajani @jinzekid @alienzh 
> 
> merged.
> sorry for taking this long, but we were very busy.
> hope you're still using this plugin :)

😁 It’s okay, we all hit some bumps now and then.
