### ISSUE TITLE
Crash on android when save same url image the second time.

### ISSUE THREAD

**Issue by beeth0ven** [CarnegieTechnologies/gallery_saver#51]
Hi, there.

Thanks for provide this life save library.

I've faced an issue when save same url image the second time.

Logs shows:

```
2020-04-03 09:51:08.036 E: Error inserting _data=/storage/emulated/0/Pictures/share_picture.png parent=6 _display_name=share_picture.png format=14347 title=share_picture.png bucket_id=-1617409521 _size=415694 date_added=1585878668 datetaken=1585878668033 date_modified=1585878659 mime_type=image/png media_type=1 bucket_display_name=Pictures
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: files._data (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1564)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1433)
        at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:2433)
        at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:2628)
        at com.android.providers.media.MediaProvider.insert(MediaProvider.java:1940)
        at android.content.ContentProvider$Transport.insert(ContentProvider.java:266)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:152)
        at android.os.Binder.execTransact(Binder.java:733)
```

It seems same url will use same filename then same primary key in SQLite, which will throw `SQLITE_CONSTRAINT_UNIQUE1`.

If we can handle this at libary level, bellow are some improvements:

    1. provide filename parameter when save image or video
    2. throw error back to developer instead of crash app

Thanks for any opinions.

**Comment by nemoryoliver** [comment]
Same here

**Comment by kingdg25** [comment]
Same here, crashes when same url image save.
