### ISSUE TITLE
fatal exception: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by emptyopen** [CarnegieTechnologies/gallery_saver#95]
I see a few of these that are marked as closed and to try the latest version, which I believe I've done? `gallery_saver: ^2.0.3`

I realized while I was writing this issue that I wasn't using the full path to the image I was trying to save, and when I corrected the path I was able to save the file properly. However, I don't think crashing the app is really acceptable behavior for an incorrect filename so I'll submit this anyways, feel free to close it if I'm missing something. Surely there must be an elegant way to catch the exception without crashing the app? 

```
E/AndroidRuntime(25429): FATAL EXCEPTION: main
E/AndroidRuntime(25429): Process: com.example.everyone_look_at_the_camera, PID: 25429
E/AndroidRuntime(25429): java.io.FileNotFoundException: ELATC-2021-02-13T22-01-13-202601.png: open failed: ENOENT (No such file or directory)
E/AndroidRuntime(25429): 	at libcore.io.IoBridge.open(IoBridge.java:492)
E/AndroidRuntime(25429): 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
E/AndroidRuntime(25429): 	at carnegietechnologies.gallery_saver.FileUtils.getBytesFromFile(FileUtils.kt:221)
E/AndroidRuntime(25429): 	at carnegietechnologies.gallery_saver.FileUtils.insertImage(FileUtils.kt:47)
E/AndroidRuntime(25429): 	at carnegietechnologies.gallery_saver.GallerySaver$saveMediaFile$1$success$1.invokeSuspend(GallerySaver.kt:69)
E/AndroidRuntime(25429): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(25429): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
E/AndroidRuntime(25429): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
E/AndroidRuntime(25429): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
E/AndroidRuntime(25429): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
E/AndroidRuntime(25429): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
E/AndroidRuntime(25429): 	at libcore.io.Linux.open(Native Method)
E/AndroidRuntime(25429): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
E/AndroidRuntime(25429): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
E/AndroidRuntime(25429): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
E/AndroidRuntime(25429): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7546)
E/AndroidRuntime(25429): 	at libcore.io.IoBridge.open(IoBridge.java:478)
E/AndroidRuntime(25429): 	... 9 more
I/Process (25429): Sending signal. PID: 25429 SIG: 9
Lost connection to device.
Exited (sigterm)
```

**Comment by Quietly-20201113** [comment]
gallery_saver 2.3.2
android 11
/data/user/0/com.example.webview_test/cache/00981661947642972.mp4: open failed: ENOENT (No such file or directory)

还是会出现这个问题
